name: Update GitHub Activity

on:
  schedule:
    - cron: "0 0 * * *" # Berjalan otomatis 1x sehari
  workflow_dispatch: # Memungkinkan Anda menjalankan secara manual dari tab Actions

jobs:
  update-readme:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
        with:
          COMMIT_MSG: "📝 Update recent activity [skip ci]"
          MAX_LINES: 5
