name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 * * * *' # Setiap jam
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README with recent GitHub activity
        uses: Readme-Workflows/recent-activity@v2.5.1
        with:
          GH_USERNAME: Bangkah
          COMMIT_MSG: "chore: Update recent activity in README"
          MAX_LINES: 7
