name: Waka Readme

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          show_title: true
          time_range: last_7_days
          show_time: true
          show_total: true
          commit_message: "Updated WakaTime stats [skip ci]"
