name: Waka Readme

on:
  schedule:
    - cron: '0 * * * *' # Update tiap jam
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    permissions:
      contents: write  # penting agar bisa update README.md
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          show_title: true
          time_range: last_7_days
          show_time: true
          show_total: true
